export enum UserRole {
  ADMIN = 'ADMIN',
  FULFILLMENT = 'FULFILLMENT',
  SUBMITTER = 'SUBMITTER',
}

export enum OrderStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
